### ISSUE TITLE
[Learn]: be{4,}r doesn't pick beeeer

### ISSUE THREAD

**Issue by symbiont-emilio-grande** [aykutkardas/regexlearn.com#102]
**Step Number:** `21`
**Step Name:** `steps.quantifierMin.title`
**Language:** `en`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36`

---

**What is the problem you are experiencing?**

**Comment by aykutkardas** [comment]
I think you're trying the wrong answer. You can try this.
![image](https://user-images.githubusercontent.com/7966133/145461697-831d2f46-1b3d-4093-b178-2b48b90c7c6d.png)

If the issue is not about the correctness of the answer, please share the screenshot.
