### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by AGM-33rus** [aykutkardas/regexlearn.com#104]
**Step Number:** `2`
**Step Name:** `steps.basicMatchers.title`
**Language:** `ru`

**User Agent:** 
`Mozilla/5.0 (Linux, Android 10, Redmi Note 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.101 Mobile Safari/537.36`

---

**What is the problem you are experiencing?**

**Comment by AGM-33rus** [comment]
ошибка соответствия, запрашиваемого и вводимого текста

**Comment by aykutkardas** [comment]
> ошибка соответствия, запрашиваемого и вводимого текста

Are you sure you are using the Latin alphabet?

**Comment by LWJerri** [comment]
Works perfectly! I think we can close this issue.

**Comment by LWJerri** [comment]
@AGM-33rus, you can reopen the issue if you are stuck in this step and we help you solve your problem, but now you don't provide any other information.
