### ISSUE TITLE
[Learn]: Input OK failed to successfully unlock the next level

### ISSUE THREAD

**Issue by Ikaros-521** [aykutkardas/regexlearn.com#107]
**Step Number:** `0`
**Step Name:** `steps.starter.title`
**Language:** `en`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3879.400 QQBrowser/10.8.4552.400`

---

**Input OK failed to successfully unlock the next level?**
[https://regexlearn.com/learn](https://regexlearn.com/learn) and [https://regexlearn-com.vercel.app/zh/learn](https://regexlearn-com.vercel.app/zh/learn)，This problem exists on both pages
![image](https://user-images.githubusercontent.com/40910637/145780704-e200ea24-6fee-4312-9f3a-2ab8a186126d.png)

**Comment by Ikaros-521** [comment]
can run normally with chrome

**Comment by aykutkardas** [comment]
Why was the issue closed? 🤔  @Ikaros-521

**Comment by Ikaros-521** [comment]
> 
I found that my browser was incompatible, which led to the JS running error

**Comment by aykutkardas** [comment]
> > Why was the issue closed? 🤔 @Ikaros-521
> 
> I found that my browser was incompatible, which led to the JS running error

Thank you for the feedback. ✨

**Comment by Ikaros-521** [comment]
> > > Why was the issue closed? 🤔 @Ikaros-521
> > 
> > 
> > I found that my browser was incompatible, which led to the JS running error
> 
> Thank you for the feedback. ✨

Great project, very helpful, thank you very much
