### ISSUE TITLE
Learn: Adım Tamamlandı

### ISSUE THREAD

**Issue by LIIIs4ma** [aykutkardas/regexlearn.com#109]
Adım Tamamlandı kısmı tasarım açısından bence hatalı, altındaki ilerleme barının hızlıca ilerlemesi kullanıcıyı anlamadan hemen geçmeye teşvik ediyor. Süre uzatılmalı ya da ilerleme barı kaldırılmalı diye düşünüyorum. 

Bu arada proje harika. 🐱‍💻

**Comment by aykutkardas** [comment]
Bu konuda haklısın, adım geçişleri arasında bu kısmı kaldırmak planlarım arasındaydı. Doğru cevaptan sonra dikkati `Sonraki` butonuna çekecek yeni bir planım var.

**Comment by LIIIs4ma** [comment]
Takipteyim. Başarılar.

**Comment by aykutkardas** [comment]
Adım tamamlamayı bildiren bileşen tamamen kaldırıldı. Adım tamamlandığında açılan kilit ikonu yukarı aşağı sallanıp sonraki adıma geçmek için dikkati üzerine çekiyor.
