### ISSUE TITLE
cheatsheet page 

### ISSUE THREAD

**Issue by ZerrinBostan** [aykutkardas/regexlearn.com#115]
In the Cheatsheet field, the field appears to be missing when the text is long
![unknown](https://user-images.githubusercontent.com/46298014/146598389-9450576a-a343-43bc-9955-68ac4122b065.png)
.

**Comment by aykutkardas** [comment]
Fixed with [this commit](https://github.com/aykutkardas/regexlearn.com/commit/551f4e88fc5b568d2108f08fa67b12d0de7dd184)
