### ISSUE TITLE
issue with step 47

### ISSUE THREAD

**Issue by LimestaX** [aykutkardas/regexlearn.com#117]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64, rv:95.0) Gecko/20100101 Firefox/95.0`

---

**What is the problem you are experiencing?**

seems that $ works but \\$ doesn't in step 47

**Comment by aykutkardas** [comment]
I could not observe this problem. Also, I'm closing this issue because there are no other comments supporting this issue. If the problem persists, please reopen with more information.

Thank you for feedback.
