### ISSUE TITLE
[Learn]: Coding problem on zh-cn

### ISSUE THREAD

**Issue by LQBlog** [aykutkardas/regexlearn.com#120]
**Step Number:** `13`
**Step Name:** `examples.range.title`
**Language:** `zh-cn`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.57`

---

**What is the problem you are experiencing?**
I entered the correct answer, but I couldn't recognize it because of the coding problem.

**Comment by aykutkardas** [comment]
Can you explain the coding problem?
