### ISSUE TITLE
[Learn]: Wrong translation in Chinese for Q11

### ISSUE THREAD

**Issue by dingar** [aykutkardas/regexlearn.com#121]
**Step Number:** `11`
**Step Name:** `examples.characterSet.title`
**Language:** `zh-cn`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.57`

---

**What is the problem you are experiencing?**
Wrong translation in Chinese.

> Write the phrase that matches each word in the text. The only characters that change are the initials of the words.
> 写出匹配文本中所有单词的表达式。单词首字母是唯一变化的字符。

**Comment by aykutkardas** [comment]
Do you want to check? @isPoto

**Comment by isPoto** [comment]
Thanks for the correction, it has been adopted and launched PR
