### ISSUE TITLE
[Learn]: Grammar problem in `steps.asterisk.title` [zh-cn]

### ISSUE THREAD

**Issue by bigboss95** [aykutkardas/regexlearn.com#123]
**Step Number:** `17`
**Step Name:** `steps.asterisk.title`
**Language:** `zh-cn`

**User Agent:** 
`Mozilla/5.0 (iPhone, CPU iPhone OS 14_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1`

---

**What is the problem you are experiencing?**

星号 *
我们在字符后面加上 *，表示一个字符完全不匹配或可以匹配多次。例如，表示字母 e 在下方文本中不出现，只出现一次或者并排出现多次。

是不是应该为：只出现【0】次或者并排出现多次

**Comment by aykutkardas** [comment]
Please check. ✨  @isPoto

**Comment by isPoto** [comment]
Already revised, thanks.
