### ISSUE TITLE
[Learn]: The letters in the character set should be unordered

### ISSUE THREAD

**Issue by gaojr** [aykutkardas/regexlearn.com#125]
**Step Number:** `4`, `11`
**Step Name:** `steps.characterSet.title`,`examples.characterSet.title`
**Language:** `zh-cn`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53`

---

Both `[aeiou]` and `[eaiou]` are correct answers, but now we can only go to the next question with `[aeiou]`.

![image](https://user-images.githubusercontent.com/18600387/147069843-80d6bdea-53f4-4aee-bd1e-21ad418c322d.png)

![image](https://user-images.githubusercontent.com/18600387/147069559-815de721-7c76-46bf-aeff-594defceccd1.png)

**Comment by aykutkardas** [comment]
Fixed 🎉
