### ISSUE TITLE
I did exactly what is in the hint but it is invalid

### ISSUE THREAD

**Issue by Yukooo** [aykutkardas/regexlearn.com#127]

**Comment by aykutkardas** [comment]
Can you provide more information?

In which step, in which language, and in which browser.

Additionally, a screenshot would be great.

**Comment by Yukooo** [comment]
After some attempts I've found that there is a sign like this one "(?=>ABC) is not working with safari" but I was using Opera for iOS and there was not such warning. I've managed to get that sign when I enabled "version for desktop "

**Comment by aykutkardas** [comment]
Got it, I'll fix the issue of the warning not appearing. Thanks for your feedback. ✨

**Comment by aykutkardas** [comment]
https://github.com/aykutkardas/regexlearn.com/issues/156
