### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by tandor71** [aykutkardas/regexlearn.com#129]
**Step Number:** `4`
**Step Name:** `steps.characterSet.title`
**Language:** `en`

**User Agent:** 
`Mozilla/5.0 (iPhone, CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/96.0.4664.116 Mobile/15E148 Safari/604.1`

---

**What is the problem you are experiencing?**
Did not accept the answer you show

**Comment by aykutkardas** [comment]
Can you share a screenshot about it? @tandor71
