### ISSUE TITLE
[Learn]: highlight character does not match.

### ISSUE THREAD

**Issue by Fc-Sanc** [aykutkardas/regexlearn.com#131]
**Step Number:** `50`
**Step Name:** `steps.flagsGlobal.title`
**Language:** `zh-cn`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62`

---

**What is the problem you are experiencing?**

the highlighted character `'i'` in `case insenstive` label should be the `'c'` in the front of `'case'` actually.
same problem in step 51 & 52.

**Comment by hao951029** [comment]
gmi is correct, it represents the modifier

**Comment by aykutkardas** [comment]
This is misleading. But the correct one is still `i`

https://regexlearn.com/zh-cn/cheatsheet

![image](https://user-images.githubusercontent.com/7966133/147457507-4375f173-1506-4d57-8f1f-2cc7192b09f8.png)
