### ISSUE TITLE
[Learn]: Incorrectly worded instructions

### ISSUE THREAD

**Issue by itpropaul** [aykutkardas/regexlearn.com#133]
**Step Number:** `29`
**Step Name:** `examples.quantifierRange.title`
**Language:** `en`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`

---

**What is the problem you are experiencing?**
Currently worded like this:
Write the expression using curly braces {} that will find texts containing 4 numbers side by side.

Should be worded like this:
Write the expression using curly braces {} that will find texts containing between 1 and 4 numbers side by side.

**Comment by aykutkardas** [comment]
Related #132 , fixed. 🎉
