### ISSUE TITLE
[Learn]: Wrong task description: Curly braces - 3

### ISSUE THREAD

**Issue by manokhina** [aykutkardas/regexlearn.com#135]
**Step Number:** `29`
**Step Name:** `examples.quantifierRange.title`
**Language:** `en`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`

---

**What is the problem you are experiencing?**
The description of the question is the same as in Curly Braces - 1: 
`Write the expression using curly braces {} that will find texts containing 4 numbers side by side.`
But should be [this](https://github.com/aykutkardas/regexlearn.com/blob/main/src/localization/en/learn.json#L87):
`Write the expression using curly braces {} that will find texts containing at least 1 and at most 4 numbers side by side.`

Screenshot:
<img width="884" alt="Screen Shot 2021-12-29 at 15 20 07" src="https://user-images.githubusercontent.com/3881689/147677277-ec7871be-41b8-454d-9cf9-b32c7ffbddbb.png">

**Comment by aykutkardas** [comment]
It should look correct 

![image](https://user-images.githubusercontent.com/7966133/147686472-f98729a6-27d8-4034-853d-ac13b0b67349.png)
