### ISSUE TITLE
[Learn]: Typo?

### ISSUE THREAD

**Issue by manokhina** [aykutkardas/regexlearn.com#136]
**Step Number:** `35`
**Step Name:** `steps.escapeCharacter.title`
**Language:** `en`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`

---

**What is the problem you are experiencing?**
The text in the task is `(*) Asteriks.` not `(*) Asterisk.`.
Not sure if this is a typo or intended :)

**Comment by aykutkardas** [comment]
You are right, it has been fixed. ✨
