### ISSUE TITLE
Multiple box clicks are invalid（step 51 and 52）

### ISSUE THREAD

**Issue by Lotus-7** [aykutkardas/regexlearn.com#140]
**Step Number:** `51` and `52`
**Step Name:** `steps.flagsMultiline.title`
**Language:** `zh-cn`
**Version:** `v1.9.2`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36`

---

**What is the problem you are experiencing?**

Click invalid when I want to switch options to multiline or case insensitive.

![图片描述](https://doc.shiyanlou.com/courses/3773/1347963/32836642313cdfdf257ba2cae7a330d7-0)

![图片描述](https://doc.shiyanlou.com/courses/3773/1347963/5df1d24ec94a0ba990cf72e7f4ae03bd-0)

**Comment by aykutkardas** [comment]
Thanks @Lotus-7, for reporting it. Fixed. 🎉
