### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by BatuhanEskici** [aykutkardas/regexlearn.com#144]
**Step Number:** `13`
**Step Name:** `examples.range.title`
**Language:** `en`
**Version:** `v2.1.1`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36`

---

**What is the problem you are experiencing?**
<img width="644" alt="image" src="https://user-images.githubusercontent.com/56672867/149727190-3968cb53-1a75-4f77-94e8-02e6aadee400.png">

Even though my answer is correct I can't pass the test, I think it might be related to the spaces (13/55)

**Comment by aykutkardas** [comment]
Go back to step 6 and examine the regex.

**Comment by BatuhanEskici** [comment]
Sorry, my bad :(

**Comment by aykutkardas** [comment]
This is actually a sign that the tutorial needs improvement. Your feedback is very valuable. I will try to make the training more memorable.
