### ISSUE TITLE
[Learn]: Correct answer doesn't validate

### ISSUE THREAD

**Issue by CreamBeam** [aykutkardas/regexlearn.com#149]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en`
**Version:** `v2.1.9`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15`

---

**What is the problem you are experiencing?**

Added the correct expression (double checked the answer) but it won't validate

**Comment by benjaminxscott** [comment]
This works for me `(?<=\$)\d+` , which is also the same as the revealed answer I believe?

**Comment by aykutkardas** [comment]
> This works for me `(?<=\$)\d+` , which is also the same as the revealed answer I believe?

Yes, that's the answer that should be.

Having trouble using this answer? @CreamBeam

**Comment by aykutkardas** [comment]
https://github.com/aykutkardas/regexlearn.com/issues/156
