### ISSUE TITLE
Lookbehinds in Cheatsheet are not highlighted

### ISSUE THREAD

**Issue by SimplyDanny** [aykutkardas/regexlearn.com#154]
![Screenshot 2022-01-26 at 23 05 13](https://user-images.githubusercontent.com/16365760/151255139-5f38e9b4-ca2d-455a-ba7e-c60eda6c4d0f.png)

While the Lookaheads work well, both Lookbehind examples show no highlighting of matches.

**Comment by aykutkardas** [comment]
Some browsers do not support this feature. Safari is one of them. 

https://caniuse.com/js-regexp-lookbehind

**Comment by SimplyDanny** [comment]
You are right. It works in Firefox but not in Safari.
