### ISSUE TITLE
48/56 positive lookbehind does not work

### ISSUE THREAD

**Issue by AndreasHoersken** [aykutkardas/regexlearn.com#156]

**Comment by aykutkardas** [comment]
Which browser are you using? If it's Safari, the following warning should appear.

![CleanShot 2022-01-29 at 23 25 37@2x](https://user-images.githubusercontent.com/7966133/151676488-d6749773-5e3b-4488-919b-28f64dd56187.png)

**Comment by eftychis** [comment]
Same issue with firefox. In iOS no warning appears.

**Comment by aykutkardas** [comment]
Added a button and warning that will appear in every browser for this step. You can now skip this step on browsers you're having trouble with.
