### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by efeertugrul** [aykutkardas/regexlearn.com#158]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en`
**Version:** `v2.3.3`

**User Agent:** 
`Mozilla/5.0 (iPhone, CPU iPhone OS 15_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Mobile/15E148 Safari/604.1`

---

**What is the problem you are experiencing?**
Does not accept the answer. Even if I copied from the hint.

**Comment by efeertugrul** [comment]
already has another issue

**Comment by aykutkardas** [comment]
https://github.com/aykutkardas/regexlearn.com/issues/156
