### ISSUE TITLE
[Lang]: Add French 🇫🇷 localization support 

### ISSUE THREAD

**Issue by Rajekevin** [aykutkardas/regexlearn.com#159]
Hello @aykutkardas 👋

I am interest to contribute for translating in french !

PS: Great Job for this awesome project !

**Comment by aykutkardas** [comment]
Great, you can start anytime by opening a PR. I hope someone will come along to help. If there is anything you want to ask, I can answer right away.

I'm glad you like the project.

**Comment by aykutkardas** [comment]
Now available in French.

https://regexlearn.com/fr
