### ISSUE TITLE
[Learn]: another option to solve the stage

### ISSUE THREAD

**Issue by Liortenne** [aykutkardas/regexlearn.com#160]
**Step Number:** `34`
**Step Name:** `steps.pipeCharacter.title`
**Language:** `en`
**Version:** `v2.3.3`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`

---

why not solve this stage like this?
(C|c|r)at

**Comment by aykutkardas** [comment]
There is no difference in usage between `(C|c)at` and `(C|c|r)at`, and you won't learn anything new.

But the following example `|` also includes a different way of using this operator. In this way, you gain a wider perspective.
`(C|c)at|rat`
