### ISSUE TITLE
[Learn]: ambiguous instructions on Practice:Asterisk* lesson

### ISSUE THREAD

**Issue by cloudgo-servicenow** [aykutkardas/regexlearn.com#161]
**Step Number:** `24`
**Step Name:** `examples.asterisk.title`
**Language:** `en`
**Version:** `v2.3.3`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10.15, rv:97.0) Gecko/20100101 Firefox/97.0`

---

**What is the problem you are experiencing?**

Current challenge is ambiguous -- it currently states: 
_Use the asterisk * to write the expression that will select each word, suitable for the absence of the letter e in the text and the presence of more than one._

But the solution is to match all 3 examples, so it should read:

_Use the asterisk * to write the expression that will select each word, suitable for the absence of the letter e in the text and the presence of **one or more.**_

As currently written, it implies that the expression should match "dp" and "deep" but not "dep"

**Comment by aykutkardas** [comment]
Fixed with version 2.4.3.
