### ISSUE TITLE
[Lang]: Add German 🇩🇪, Dari, and Pashto 🇦🇫  localization support!

### ISSUE THREAD

**Issue by Hedayat-Farahi786** [aykutkardas/regexlearn.com#164]
Hey dear @aykutkardas !

I would like to contribute to the project by adding the `German`, `Dari`, `Pashto` Languages.
By the way Great job for building such an awesome project! 👏

**Comment by aykutkardas** [comment]
Hi @Hedayat-Farahi786 👋🏻  , this is a very broad issue.

You can start by just addressing this in `German`. I'm excited to see your contributions. ✨
