### ISSUE TITLE
Fix responsive problems

### ISSUE THREAD

**Issue by aykutkardas** [aykutkardas/regexlearn.com#17]
We need a better layout for responsive.

![image](https://user-images.githubusercontent.com/7966133/136696978-5885b2be-e45c-4c7b-81e8-5235f1862a5e.png)

**Comment by panvicka** [comment]
Hi, I would like to work on this.

**Comment by aykutkardas** [comment]
> Hi, I would like to work on this.

Be sure to send small pull requests with minor changes. Thank you for your interest.

**Comment by LuizHAP** [comment]
@aykutkardas u need to add hacktoberfest to your project to work this issues

**Comment by aykutkardas** [comment]
Can you explain? @LuizHAP

**Comment by LuizHAP** [comment]
> Can you explain? @LuizHAP

In your project, u need to add hacktoberfest label.
See on Google, because all this issues doesn't work for Hacktoberfest if you don't do this

**Comment by aykutkardas** [comment]
I added, thanks. @LuizHAP

**Comment by panvicka** [comment]
I tried to make a draft of the design for a small device and a table.t Would you like something like this or do you have an another idea? 

![iPad Pro 11_ - 2](https://user-images.githubusercontent.com/64703124/136833074-ba32e623-2f69-4bec-8dd6-2970540610c6.png)
![iPad Pro 11_ - 3](https://user-images.githubusercontent.com/64703124/136833075-fd7f6540-80bf-4a76-9c5a-0e288d49cf61.png)
![iPhone SE - 2](https://user-images.githubusercontent.com/64703124/136833078-10bef017-5215-48d9-bdd4-206778703792.png)
![iPhone SE - 1](https://user-images.githubusercontent.com/64703124/136833077-bbbdf76b-6153-46d8-b7f8-16298740dc77.png)

**Comment by aykutkardas** [comment]
Some fonts appear too small to be read. What screen sizes did you use? @panvicka

**Comment by aykutkardas** [comment]
@panvicka I get it, I don't think they're good enough. Font sizes and spacing are disproportionate and unsightly.
