### ISSUE TITLE
USERNAME_REGEX

### ISSUE THREAD

**Issue by hamine75** [aykutkardas/regexlearn.com#176]
**Step Number:** `2`
**Step Name:** `steps.basicMatchers.title`
**Language:** `en`
**Version:** `v2.5.0`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46`

---

**What is the problem you are experiencing?**

**Comment by aykutkardas** [comment]
Can you explain the problem?

**Comment by hamine75** [comment]
I M begginer in bash, how can i find regex of username, group, home_folser and password, thanks
USERNAME_REGEX=""
 GROUP_REGEX=""
HOME_FOLDER_REGEX=""
PASSWORD_REGEX=""

**Comment by aykutkardas** [comment]
This is not the right place for that. Please try to google it.
