### ISSUE TITLE
[Learn]: description text in codeblock

### ISSUE THREAD

**Issue by Tealk** [aykutkardas/regexlearn.com#181]
**Step Number:** `32`
**Step Name:** `steps.groupReference.title`
**Language:** `de`
**Version:** `v2.6.3`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64, rv:99.0) Gecko/20100101 Firefox/99.0`

---

**What is the problem you are experiencing?**
![grafik](https://user-images.githubusercontent.com/12276250/164001451-501d663a-d75b-4854-849d-11559df64200.png)

the "ein" does not belong in the codeblock

**Comment by aykutkardas** [comment]
Fixed.
