### ISSUE TITLE
[Learn]: "number" word choice problematic

### ISSUE THREAD

**Issue by YummyGyros** [aykutkardas/regexlearn.com#182]
**Step Number:** `27`
**Step Name:** `examples.quantifier.title`
**Language:** `en`
**Version:** `v2.7.0`

**User Agent:** 
`Mozilla/5.0 (X11, Ubuntu, Linux x86_64, rv:99.0) Gecko/20100101 Firefox/99.0`

---

**What is the problem you are experiencing?**

"4 consecutive numbers" isn't the most explicit and made me believe I had to find 4 "words" and not one "word" of 4 **digits**

**Comment by aykutkardas** [comment]
I think this step is clear enough. If I get similar feedback I'll improve it.
