### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by kreeedit** [aykutkardas/regexlearn.com#183]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en`
**Version:** `v2.7.1`

**User Agent:** 
`Mozilla/5.0 (X11, Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`

---

**What is the problem you are experiencing?**
The solution ((?<=\$)\d+) is not accepted

**Comment by aykutkardas** [comment]
Does this warning appear?

![image](https://user-images.githubusercontent.com/7966133/165700981-68660945-eb64-4389-bf6c-1539da876703.png)

**Comment by kreeedit** [comment]
As far as I remember, I can not see this warning, however after I reloaded
the page, I could go to the next task.

Aykut Kardaş ***@***.***> ezt írta (időpont: 2022. ápr. 28.,
Cs, 9:34):
