### ISSUE TITLE
[Learn]: Match not being highlighted

### ISSUE THREAD

**Issue by Begus001** [aykutkardas/regexlearn.com#184]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en`
**Version:** `v2.7.1`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`

---

**What is the problem you are experiencing?**

The match is not being highlighted despite entering the correct expression.

<img width="980" alt="image" src="https://user-images.githubusercontent.com/43996495/165972621-3ace3d39-0b05-4f35-84e7-3d467447de9a.png">

**Comment by aykutkardas** [comment]
Fixed. 🎉
