### ISSUE TITLE
[Learn]: Regex pattern not accepting

### ISSUE THREAD

**Issue by hamzashehzad09** [aykutkardas/regexlearn.com#185]
**Step Number:** `4`
**Step Name:** `steps.characterSet.title`
**Language:** `en`
**Version:** `v2.7.1`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36`

---

**What is the problem you are experiencing?**

Hi,

I was trying the regex pttern to match the exercise:

Character Sets [abc]
If one of the characters in a word can be various characters, we write it in square brackets [] with all alternative characters. For example, to write an expression that can find all the words in the text, type the characters a, e, i, o, u adjacently within square brackets [].

Your answer: b[aeiou]r
My answer: b[a|e|i|o|u]r

Somehow it is not accepting my answer , i believe it is right as i have tried it online on other tools as well
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/59653806/166216045-68476a78-690b-4b13-b0ee-55f02b396668.png">

**Comment by aykutkardas** [comment]
Why do you want to use the `|` or operator, which is not needed here? The expression you typed chooses the correct words, so it appears yellow but is incorrect as an answer. Because the or operators are unnecessary.
