### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by vonkoff** [aykutkardas/regexlearn.com#186]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en`
**Version:** `v2.7.1`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15`

The text that is selected is not highlighted even though the correct answer is inputted. 

![Screen Shot 2022-05-02 at 10 28 47 AM](https://user-images.githubusercontent.com/16548992/166251585-f7584618-901d-4888-96f7-edc4157da33e.png)

**Comment by aykutkardas** [comment]
Follow this issue #184
