### ISSUE TITLE
FIX: Superfluous word

### ISSUE THREAD

**Issue by iosakurov** [aykutkardas/regexlearn.com#187]
https://github.com/aykutkardas/regexlearn.com/blob/4c7f4f9030756f0139696ac34373cd9d9d9e4264/src/localization/ru/learn.json#L87

Hello, this word `мере` is superfluous, in this context it is inappropriate

Bad translation:
"Напишите выражение, используя фигурные скобки {}, чтобы выбирать числа от 0 до 9 в тексте, которые находится мере между 1 и 4."

Good translation:
"Напишите выражение, используя фигурные скобки {}, чтобы выбирать числа от 0 до 9 в тексте, которые находится между 1 и 4."

**Comment by aykutkardas** [comment]
What do you think of this translation improvement? @LWJerri

**Comment by LWJerri** [comment]
Hello. Yea, it's good improvement. I missed remove word "мере".

**Comment by aykutkardas** [comment]
Fixed @iosakurov, thanks for your feedback.
