### ISSUE TITLE
[Learn]: Another right answer for No.31

### ISSUE THREAD

**Issue by sheeeeep** [aykutkardas/regexlearn.com#190]
**Step Number:** `31`
**Step Name:** `steps.groupping.title`
**Language:** `zh-cn`
**Version:** `v2.7.8`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36`

---

**What is the problem you are experiencing?**

I think /(ha{2,})/g is also a right answer.

**Comment by aykutkardas** [comment]
You're right, that's a correct answer too. But this is training, not a test. Therefore, it is expected that the method taught in that step will be used.
