### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by Lola58** [aykutkardas/regexlearn.com#201]
**Step Number:** `13`
**Step Name:** `lesson.regexForSeo.robots.title`
**Language:** `zh-cn`
**Version:** `v2.7.8`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**
.pdf$  rather than /*.pdf$, 
The former is simpler than the latter

**Comment by aykutkardas** [comment]
Examples for robots.txt files are as in this step.
