### ISSUE TITLE
[Learn]: "Atleast" word is causing some confusion

### ISSUE THREAD

**Issue by ArunEdathadan** [aykutkardas/regexlearn.com#202]
**Step Number:** `28`
**Step Name:** `examples.quantifierMin.title`
**Language:** `en`
**Version:** `v2.7.8`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`

---

"Write the expression using curly braces {} that will find texts containing at least 2 numbers side by side."
this sentence could be ->
"Write the expression using curly braces {} that will find texts containing 2 or more numbers side by side."

May be this is purely due to inefficiency in my language proficiency.

**Comment by aykutkardas** [comment]
I think the text here is sufficient. If a similar comment comes in, I'll consider your suggestion. Thank you for feedback.
