### ISSUE TITLE
[Learn]: The description is not clear

### ISSUE THREAD

**Issue by ArunEdathadan** [aykutkardas/regexlearn.com#203]
**Step Number:** `33`
**Step Name:** `steps.nonCapturingGroupping.title`
**Language:** `en`
**Version:** `v2.7.8`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**

**Comment by aykutkardas** [comment]
Duplicate #174
