### ISSUE TITLE
[Learn]: Pipe Character | solution

### ISSUE THREAD

**Issue by jurajkapsz** [aykutkardas/regexlearn.com#210]
**Step Number:** `34`
**Step Name:** `steps.pipeCharacter.title`
**Language:** `en`
**Version:** `v2.8.0`

**User Agent:** 
`Mozilla/5.0 (X11, Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36`

---

**What is the problem you are experiencing?**
Not sure if the proposed solution example is the best one or natural.

I was doing the `Pipe Character |` regex tutorial on a text string
```
cat Cat rat
```
which starts as
```
/(C|c)at/g
```
and the result is expected to be
```
/(C|c)at|rat/g
```
but I wrote
```
/(C|c|r)at/g
```
which came as more natural to me as we were also just introduced `()` capturing groups and given the similarities of the words `cat` and `rat`, for which I didn't expect I would write `/(C|c)at|rat/g`. Being it other words like eg `cat dog`, I'd go for it.

**Comment by aykutkardas** [comment]
This step has been updated.
![image](https://user-images.githubusercontent.com/7966133/194802879-7a3d0247-0d2f-42d4-bba9-d53122a694e4.png)
