### ISSUE TITLE
[Learn]: regex101

### ISSUE THREAD

**Issue by AW1534** [aykutkardas/regexlearn.com#211]
**Step Number:** `33`
**Step Name:** `steps.nonCapturingGroupping.title`
**Language:** `en`
**Version:** `v2.8.0`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37`

---

**What is the problem you are experiencing?**
This section doesn't say what to do

**Comment by aykutkardas** [comment]
Duplicate #174
