### ISSUE TITLE
[Learn]: Unable to proceed after Step47 in Chrome.

### ISSUE THREAD

**Issue by lineyha** [aykutkardas/regexlearn.com#213]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en`
**Version:** `v2.8.0`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**
Merhaba, Chrome tarayıcı kullanıyorum. 48. aşamada 'You can click here.' kısmına tıkladığımda diğer aşamaya geçmedi. Gayet temiz, güzel bir site yapmışsınız. Tebrik ediyorum bu arada.

**Comment by aykutkardas** [comment]
Merhaba, bunun ilgili bir issue mevcuttur. #193 

Bunu kısa süre sonra fixleyeceğim. Diğer issue dan takip edebilirsiniz.
