### ISSUE TITLE
regex may be false

### ISSUE THREAD

**Issue by tudousiZzz** [aykutkardas/regexlearn.com#217]
**Step Number:** `13`
**Step Name:** `lesson.regexForSeo.robots.title`
**Language:** `en`
**Version:** `v2.12.6`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**

this is web link of regexlearn.com
https://regexlearn.com/learn/regex-for-seo

User-agent: *
Disallow: /*.pdf$

----------

/about.html
/home.html
/document.pdf
/team.html
/introduction.pdf

`/*.pdf$` whether should be `/.*pdf$` ?

**Comment by aykutkardas** [comment]
What is shown in this step is not a regex. It is a similar syntax. It is known as the wildcard.

That's why the title of my name is `robots.txt (regex-like syntax)`.

If it was regex, your suggestion was correct.
