### ISSUE TITLE
For the section `Study`, should we add a directory?

### ISSUE THREAD

**Issue by mohalikeyou** [aykutkardas/regexlearn.com#218]
For the section `Study`, should we add a directory?
If I needed  to review the previous card, I would have to tap the previous step repeatedly, that's so boring...

**Comment by aykutkardas** [comment]
Index added. ✨ 
![image](https://user-images.githubusercontent.com/7966133/215676772-d7c2db3b-4312-4c43-b51e-178c8a0e7a7c.png)
