### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by rmpaschal** [aykutkardas/regexlearn.com#226]
**Step Number:** `5`
**Step Name:** `lesson.regexForSeo.any.title`
**Language:** `en`
**Version:** `v2.13.1`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**
Writing the correct answer but the app does not allow me to continue.

**Comment by aykutkardas** [comment]
Can you share your step answer?
