### ISSUE TITLE
[Learn]: Unclear action end user

### ISSUE THREAD

**Issue by ardelean94** [aykutkardas/regexlearn.com#238]
**Step Number:** `33`
**Step Name:** `steps.nonCapturingGroupping.title`
**Language:** `en`
**Version:** `v2.14.3`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64, rv:104.0) Gecko/20100101 Firefox/104.0`

---

**What is the problem you are experiencing?**
The task on this step is unclear and unless "Show Answer" cannot go further either since the the task is not unlocked.

**Comment by aykutkardas** [comment]
Duplicate https://github.com/aykutkardas/regexlearn.com/issues/174
