### ISSUE TITLE
[Lang]: Translation mistake

### ISSUE THREAD

**Issue by foteev** [aykutkardas/regexlearn.com#239]
**Step Number:** `29`
**Step Name:** `examples.quantifierRange.title`
**Language:** `ru`
**Version:** `v2.14.3`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**

Hi. Thanks for your work. A little mistake here in translation, that leads to misunderstanding in "Repetitions: Curly Braces-3": 
"Напишите выражение, используя фигурные скобки {}, чтобы выбирать числа от 0 до 9 в тексте, которые находится между 1 и 4."
Should be written:
"Напишите выражение, используя фигурные скобки {}, чтобы выбирать числа от 0 до 9 в тексте, длиной от 1 до 4 знаков."

**Comment by aykutkardas** [comment]
What do you think about this suggestion? @LWJerri

**Comment by foteev** [comment]
> > Напишите выражение, используя фигурные скобки '{}', чтобы выбрать числа от 0 до 9 в тексте, длиной от 1 до 4 знаков.
> 
> Do you agree with this suggestion? @foteev

That's fine.

**Comment by aykutkardas** [comment]
Thanks for your contribution. @foteev @LWJerri  

Fixed.
