### ISSUE TITLE
[Learn]: Enter is not working even when filled as [a,e,i,o,u]

### ISSUE THREAD

**Issue by prateekbhaskar** [aykutkardas/regexlearn.com#241]
**Step Number:** `4`
**Step Name:** `steps.characterSet.title`
**Language:** `en`
**Version:** `v2.14.4`

**User Agent:** 
`Mozilla/5.0 (X11, Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**

**Comment by aykutkardas** [comment]
Does your answer contain commas? If your answer doesn't look right and you don't see the green color in matches. Check the hint.
