### ISSUE TITLE
[Learn]: Translation support for Regex For SEO tutorial (Russian)

### ISSUE THREAD

**Issue by aykutkardas** [aykutkardas/regexlearn.com#247]
This file needs to be translated from `English` to `Russian`.

Please let me know your native language is Russianbefore undertaking this issue.

**Preview:** https://regexlearn.com/ru/learn/regex-for-seo

**File:** https://github.com/aykutkardas/regexlearn.com/blob/develop/src/localization/ru/lessons/regexForSeo.json

You will see some parts of the text as follows.
![image](https://user-images.githubusercontent.com/7966133/194122391-ac9d8464-c201-4a5e-8084-e1412d063ee0.png)

This was done to highlight a particular word.
![image](https://user-images.githubusercontent.com/7966133/194121835-fea52f8b-eab7-432a-abfc-25c73666cbf9.png)

#### NOTE:
```
`The text between quotation marks should not be translated.`
```

**Comment by danmaninc** [comment]
Hello!
I'm native Russian speaker and I can try to translate it to Russian.
Please assign this issue to me.
