### ISSUE TITLE
[Learn]: Highlighting of solution adds space/kerning to highlighted characters

### ISSUE THREAD

**Issue by vrms** [aykutkardas/regexlearn.com#255]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en`
**Version:** `v2.18.0`

**User Agent:** 
`Mozilla/5.0 (Windows NT 6.1, Win64, x64, rv:102.0) Gecko/20100101 Firefox/102.0`

---

**What is the problem you are experiencing?**
The highlighting does not only put a highlighter on the solution but also adds space ore kerning aroung the highlighted characters. That makes it less clear. 

I.e. **Step Number:** `47`

the $ stand directly in fron t of the 5 (**$5**). When highlighted it looks like **$ 5**. This does not help with the understanding.

**Comment by aykutkardas** [comment]
Thanks for your feedback. Fixed. ✨
