### ISSUE TITLE
input b[.]r    can't done

### ISSUE THREAD

**Issue by jjjjer** [aykutkardas/regexlearn.com#258]
**Step Number:** `4`
**Step Name:** `steps.characterSet.title`
**Language:** `zh-cn`
**Version:** `v2.18.2`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**

**Comment by aykutkardas** [comment]
If you follow the tutorial's recommendations, he will explain them step by step.

Checking these might give you some ideas.
https://regexlearn.com/playground?id=63733fce00768c180d5bb711
https://regexlearn.com/playground?id=63733fe968a2c25426986483

If you get stuck on a step, check the hint.
![image](https://user-images.githubusercontent.com/7966133/201857024-becde958-e7f3-4c90-9043-172b8ca24d52.png)
