### ISSUE TITLE
Doesn't work in safari.

### ISSUE THREAD

**Issue by ghost** [aykutkardas/regexlearn.com#264]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en`
**Version:** `v2.19.0`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15`

---

**What is the problem you are experiencing?**

Doesn't work in safari. Going to a different browser means having to start back at step 1. That's not a very nice UX.
Edit: same for firefox.

Seems like it ONLY works in Chrome? Then say that, instead of "doesn't work in SOME browsers", and please show this at the START of the tutorial.

**Comment by brkcrdk** [comment]
I've tested on both safari and firefox browsers and it seems working fine. I don't really know what is the problem for you. Could you give more detail about your problem. Maybe some screenshot or code snippet would help. :)
