### ISSUE TITLE
J'ai remplis les conditions demandées mais vous n'avez pas accepté ma réponse. C'est un bug ou soit c'est toujours pareil ?

### ISSUE THREAD

**Issue by Annette-Bwemere-Salama** [aykutkardas/regexlearn.com#270]
![Screenshot_20221216-124528.jpg](https://user-images.githubusercontent.com/74765874/208081751-931afc28-da84-4890-841e-f7e081d909e9.jpg)

**Comment by aykutkardas** [comment]
You can look at the hint to see the correct answer.

![image](https://user-images.githubusercontent.com/7966133/208089119-c670cdba-a429-44c8-8899-7012053f1069.png)
