### ISSUE TITLE
Don't read quantifier 

### ISSUE THREAD

**Issue by ihareg** [aykutkardas/regexlearn.com#279]
**Step Number:** `11`
**Step Name:** `examples.characterSet.title`
**Language:** `en`
**Version:** `v2.20.1`

**User Agent:** 
`Mozilla/5.0 (X11, Linux x86_64, rv:108.0) Gecko/20100101 Firefox/108.0`

---

**What is the problem you are experiencing?**

beer deer feer

is not chosen in case:
 [bdf]e{2}r 
 is input.

**Comment by aykutkardas** [comment]
These colours would be red if your solution was wrong. The teacher waits for the answer he teaches from you. So it should be answered as expected.

There are countless ways to get something right in Regex. If each were allowed, you could not be sure of learning correctly.

![image](https://user-images.githubusercontent.com/7966133/212467691-633d467f-465b-4a83-ba92-1ac93284d668.png)
