### ISSUE TITLE
Don't read a dot

### ISSUE THREAD

**Issue by ihareg** [aykutkardas/regexlearn.com#280]
**Step Number:** `12`
**Step Name:** `examples.negatedCharacterSet.title`
**Language:** `en`
**Version:** `v2.20.1`

**User Agent:** 
`Mozilla/5.0 (X11, Linux x86_64, rv:108.0) Gecko/20100101 Firefox/108.0`

---

**What is the problem you are experiencing?**

Given:
bear beor beer beur

A solution doesn't work:
b.[^ou]r

**Comment by aykutkardas** [comment]
These colours would be red if your solution was wrong. The teacher waits for the answer he teaches from you. So it should be answered as expected.

There are countless ways to get something right in Regex. If each were allowed, you could not be sure of learning correctly.

![image](https://user-images.githubusercontent.com/7966133/212467579-25d6dd6f-c59a-4ad7-9149-1be008f5d3f2.png)
