### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by ahumpert** [aykutkardas/regexlearn.com#282]
**Step Number:** `13`
**Step Name:** `lesson.regexForSeo.robots.title`
**Language:** `en`
**Version:** `v2.22.2`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15`

---

**What is the problem you are experiencing?**

Unable to edit form

**Comment by aykutkardas** [comment]
This is a step that cannot be edited. It can only be read.
