### ISSUE TITLE
[Learn]: Step 47- does not accept correct answer

### ISSUE THREAD

**Issue by alexkar13** [aykutkardas/regexlearn.com#284]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en`
**Version:** `v2.23.2`

**User Agent:** 
`Mozilla/5.0 (iPhone, CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/110.0.5481.114 Mobile/15E148 Safari/604.1`

---

**What is the problem you are experiencing?**

I am typing (?<=\$)\d+ inside the answer box and it doesn’t accept the answer.

**Comment by mafzaldev** [comment]
You're doing a mistake while writing the experssion. `(?<=\$)\d+` is the correct expression, while your expression is ` (?<=$)\d+` which has a difference of `\` before `$` symbol.
