### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by sunwenshuo455** [aykutkardas/regexlearn.com#286]
**Step Number:** `50`
**Step Name:** `steps.flagsGlobal.title`
**Language:** `zh-cn`
**Version:** `v2.23.2`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.69`

---

**What is the problem you are experiencing?**

答案完全一样为啥过不去

**Comment by aykutkardas** [comment]
Have you tried using flags?
![image](https://user-images.githubusercontent.com/7966133/224947500-12882519-c0fb-419d-9510-abb3623153d1.png)

**Comment by sunwenshuo455** [comment]
> 你试过使用标志吗？ ![图像](https://user-images.githubusercontent.com/7966133/224947500-12882519-c0fb-419d-9510-abb3623153d1.png)

thanks
