### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by sqw2016** [aykutkardas/regexlearn.com#294]
**Step Number:** `0`
**Step Name:** `steps.starter.title`
**Language:** `zh-cn`
**Version:** `v2.23.4`

**User Agent:** 
`Mozilla/5.0 (X11, Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36`

---

**What is the problem you are experiencing?**
can not go to next page after enter Ok

**Comment by aykutkardas** [comment]
Regex is case-sensitive. So make sure you write exactly what you are asked to write. 
`OK`
