### ISSUE TITLE
C Like Comments Not Detecting

### ISSUE THREAD

**Issue by eknoyon** [aykutkardas/regexlearn.com#302]
C Like Comments Not Detecting in playground.

EXP:
```
\/\*+[^\*\/]*\*+\/
```
TEXT:
```
/**/
/* */
/*
asdf
*/
```

**Comment by eknoyon** [comment]
```
\/\*+[^\*\/]*\*+\/
```

**Comment by aykutkardas** [comment]
What is the behaviour you expect?

The Text field is not a code editor and treats everything in it as plain text. So you can't expect to write a comment line there.

![image](https://user-images.githubusercontent.com/7966133/234857560-1a079d76-08d8-47c6-b9ba-c4e039823d7b.png)


If the problem you are talking about is something different, please explain.

**Comment by eknoyon** [comment]
Thank you. The issue is resolved.
