### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by jakusv** [aykutkardas/regexlearn.com#320]
**Step Number:** `50`
**Step Name:** `steps.flagsGlobal.title`
**Language:** `en`
**Version:** `v2.23.5`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 OPR/100.0.0.0`

---

**What is the problem you are experiencing?**

My answer match "show answer":  \w+\.com/g and next step no valid

**Comment by aykutkardas** [comment]
Please make sure you activate the following correct flags in this step.
If you need the global flag, just activate it.

![image](https://github.com/aykutkardas/regexlearn.com/assets/7966133/92bff7ff-b761-4e35-bd8e-6eb83c0d2261)

**Comment by jakusv** [comment]
Thank You! OK 😊
