### ISSUE TITLE
I couldn't write / be[^uo]r /g / be[^ou]r /g in two lines

### ISSUE THREAD

**Issue by yenehun** [aykutkardas/regexlearn.com#321]
**Step Number:** `12`
**Step Name:** `examples.negatedCharacterSet.title`
**Language:** `en`
**Version:** `v2.25.1`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64, rv:109.0) Gecko/20100101 Firefox/116.0`

---

**What is the problem you are experiencing?**

**Comment by aykutkardas** [comment]
It can be a little confusing. But these are options. Just write one of them.

<img width="607" alt="CleanShot 2023-08-29 at 16 19 45@2x" src="https://github.com/aykutkardas/regexlearn.com/assets/7966133/247d7f52-b6bf-4706-a1f7-b4c7ec4fbc94">

**Comment by yenehun** [comment]
I want you to ask  how to write it
