### ISSUE TITLE
The input box cannot be entered,Can't go to the next step

### ISSUE THREAD

**Issue by YuanGe1842348771** [aykutkardas/regexlearn.com#322]
**Step Number:** `13`
**Step Name:** `lesson.regexForSeo.robots.title`
**Language:** `zh-cn`
**Version:** `v2.25.3`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**

**Comment by aykutkardas** [comment]
You do not need to type anything in this step. This step is an explanation and example.

But I understood the problem. You can go back to the previous step and then go back to the next step or you should be able to proceed to the next step when you refresh the page.

I will fix this issue as soon as possible.

**Comment by lantiguav** [comment]
This issue was resolved
