### ISSUE TITLE
[Lang]: Add `Persian` translation

### ISSUE THREAD

**Issue by sir-kokabi** [aykutkardas/regexlearn.com#325]

**Comment by AshkanArabim** [comment]
I saw the help wanted tag. I'd love to contribute to this translation. Is RTL supported on the site?

**Comment by sir-kokabi** [comment]
I can help to translate and edit Persian translation.

**Comment by amirroox** [comment]
Can I add RTL support?
@aykutkardas

**Comment by aykutkardas** [comment]
> Can I add RTL support? @aykutkardas

Sorry for the late reply. We have had RTL support for the past few months.

**Comment by amirroox** [comment]
> > Can I add RTL support? @aykutkardas
> 
> Sorry for the late reply. We have had RTL support for the past few months. @amirroox 

Please. Thank you for your reply.  Does that mean we can add Persian translation now?

**Comment by aykutkardas** [comment]
> Please. Thank you for your reply. Does that mean we can add Persian translation now? @aykutkardas

Definitely. ✨  @amirroox
