### ISSUE TITLE
Regex SEO I can not move on át the first site

### ISSUE THREAD

**Issue by SusieBlondAI** [aykutkardas/regexlearn.com#332]
**Step Number:** `0`
**Step Name:** `lesson.regexForSeo.starter.title`
**Language:** `en`
**Version:** `v2.26.1`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**

**Comment by aykutkardas** [comment]
Could you share a screenshot of the page you are having problems with?

**Comment by SusieBlondAI** [comment]
Hello,

Thank you so much, but somehow the problem was solved.

Best regards,
Zsuzsanna

Aykut Kardaş ***@***.***> ezt írta (időpont: 2023. dec. 9.,
Szo 14:38):
