### ISSUE TITLE
Bonjour, Il y a une petite erreur

### ISSUE THREAD

**Issue by Fil2fer-vitamine** [aykutkardas/regexlearn.com#337]
**Step Number:** `43`
**Step Name:** `steps.withoutSpaceCharacter.title`
**Language:** `fr`
**Version:** `v2.28.0`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**
![Capture d'écran 2024-02-20 122829](https://github.com/aykutkardas/regexlearn.com/assets/106022045/7802f16f-7933-4b03-89a7-b1b5d0e7a396)

Bonjour, votre travail est remarquable.
Cependant, je pense qu'il y a un petit soucis à la page 44/56 : Vous dîtes "\S est utilisé pour trouver uniquement les caractères d'espace." ...
Or, d'après ce que je peux comprendre \s est utilisé pour trouver uniquement les caractères d'espace.
\S est utilisé pour trouver tous les autres caractères autre que le caractère Espace.
Est-ce correct ou ai-je mal compris ?

Hello, your work is remarkable.
However, I think there is a small problem on page 44/56: You say "\S is used to find only space characters." ...
Now from what I can understand \s is used to find only space characters.
\S is used to find all other characters other than the Space character.
Is this correct or have I misunderstood?

**Comment by aykutkardas** [comment]
Thank you for the feedback, I noticed there is an issue with the translation here. `\S` matches any non-whitespace character. 

I will correct the translation error in this step as soon as possible.

**Comment by aykutkardas** [comment]
Fixed ✅
