### ISSUE TITLE
[Learn]: is the answer wrong?

### ISSUE THREAD

**Issue by SemonWang** [aykutkardas/regexlearn.com#338]
**Step Number:** `39`
**Step Name:** `steps.withoutWordCharacter.title`
**Language:** `zh-cn`
**Version:** `v2.28.0`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**

![image](https://github.com/aykutkardas/regexlearn.com/assets/19504041/90a85883-82d9-49b0-988e-c1f6c10d1f2f)
why is it not [^\w]?

**Comment by SemonWang** [comment]
i confused w and W

**Comment by aykutkardas** [comment]
> i confused w and W

This confusion is quite normal for different alphabets. I'm glad you solved it.
