### ISSUE TITLE
[Learn]: Even the answer cannot pass the test

### ISSUE THREAD

**Issue by aaykbcn** [aykutkardas/regexlearn.com#339]
**Step Number:** `50`
**Step Name:** `steps.flagsGlobal.title`
**Language:** `zh-cn`
**Version:** `v2.29.0`

**User Agent:** 
`Mozilla/5.0 (X11, Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**
Even the answer provided cannot pass the check...

**Comment by aykutkardas** [comment]
Are you sure you selected the flag?

If you are sure, can you share a screenshot of your answer?

**Comment by aaykbcn** [comment]
> Are you sure you selected the flag?
> 
> If you are sure, can you share a screenshot of your answer?

Thank you for replying soon.
I see...just select the flag, and no need to type anything.
Unnecessarily issue...
