### ISSUE TITLE
5th Problem Can have one more answer

### ISSUE THREAD

**Issue by ketan-rathod-713** [aykutkardas/regexlearn.com#349]
**Step Number:** `4`
**Step Name:** `steps.characterSet.title`
**Language:** `en`
**Version:** `v2.29.0`

**User Agent:** 
`Mozilla/5.0 (X11, Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**
b[a,e,i,o,u]r and b[aeiou] are both answers. but if i write b[a,e,i,o,u] then it will not mark it as correct answer.
![image](https://github.com/aykutkardas/regexlearn.com/assets/76687839/8529f707-9809-4800-95e8-c5cae1954236)

While Below is correct answer already
![image](https://github.com/aykutkardas/regexlearn.com/assets/76687839/df058287-c39b-4cc0-b284-4eaaabc7f7d0)

Another Problem : Also when i click on report a problem, it automatically writes wrong step number. for eg. currently i have reported problem on step number 5 but it shows 4. for first problem it will say step number 0.

**Comment by aykutkardas** [comment]
Your answer is not correct. Commas are not used to separate characters. The steps start from 0 and is correct as the number for me to debug. Thanks for letting me know.

![image](https://github.com/aykutkardas/regexlearn.com/assets/7966133/389a4c90-a0c8-43a5-aafa-a3fc341dbb1c)
