### ISSUE TITLE
[Learn]: Wrong matching group in description

### ISSUE THREAD

**Issue by pYtoner** [aykutkardas/regexlearn.com#35]
**Step Number:** `32`
**Step Name:** `steps.groupReference.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**

   The description includes `(\d{3})` instead of `([0-9]{3})`
   The `\d` digit matching has not been shown before so it might confuse some people especially because the starting regex also uses the `[0-9]` to match digits: `([0-9]{3})-([0-9])-`

**Comment by aykutkardas** [comment]
Fixed 🎉
