### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by yw540** [aykutkardas/regexlearn.com#351]
**Step Number:** `13`
**Step Name:** `lesson.regexForSeo.robots.title`
**Language:** `zh-cn`
**Version:** `v2.29.0`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0`

---

**What is the problem you are experiencing?**
Elements on this page should perhaps maintain their states no matter what user do. When I clicked the text space, however, the state of the page turned from GREEN(allow user move to next page) to RED(lock bottom go to next page) and could not switch to GREEN again, which seems confusing.

**Comment by lantiguav** [comment]
I believe this issue is fixed now
