### ISSUE TITLE
[Learn]: Minor issue - Alternate solution not recognized

### ISSUE THREAD

**Issue by Meetlint** [aykutkardas/regexlearn.com#354]
**Step Number:** `6`
**Step Name:** `steps.range.title`
**Language:** `en`
**Version:** `v2.29.0`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`

---

On problem 7 of the first unit, the alternate solution:
/    [^a-d]+[^p-z]     /g
-is not recognized as correct, despite producing the correct output. Otherwise a wonderful learning module.

Have a lovely coding session!

**Comment by aykutkardas** [comment]
This is to make sure you follow the designed course. When you give a different answer correctly, you will see that the lock icon is yellow. This shows that you are doing it right in a different way, but you are not doing what you were taught to take to the next step.
