### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by AdiGodlner** [aykutkardas/regexlearn.com#357]
**Step Number:** `4`
**Step Name:** `steps.characterSet.title`
**Language:** `en`
**Version:** `v2.29.0`

**User Agent:** 
`Mozilla/5.0 (X11, Ubuntu, Linux x86_64, rv:125.0) Gecko/20100101 Firefox/125.0`

---

**What is the problem you are experiencing?**

the answer aeiou does not work

**Comment by aykutkardas** [comment]
Did you try asnwer `hint`?

**Comment by AdiGodlner** [comment]
hi sorry I tried answer hint and it still didn't work
I refreshed and cleared cache and then it worked
can't reproduce it sorry

‫בתאריך יום ד׳, 15 במאי 2024 ב-20:17 מאת ‪Aykut Kardaş‬‏ <‪
***@***.***‬‏>:‬

**Comment by aykutkardas** [comment]
Interesting, thank for reporting. 🙏🏻
