### ISSUE TITLE
[Learn]: \d has not been used before

### ISSUE THREAD

**Issue by pYtoner** [aykutkardas/regexlearn.com#36]
**Step Number:** `36`
**Step Name:** `steps.caret.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**

The description is:
> We were using \d to find numbers. To find only numbers at the beginning of a line, prefix this expression with the ^ sign.
    
But we did not use `\d` before we used `[0-9]`

**Comment by aykutkardas** [comment]
The order of the tutorials was later changed and some quotes are no longer valid.

Changed the sample in this step to `[0-9]`.
