### ISSUE TITLE
Practice: Negated Character Sets , Can't move next question

### ISSUE THREAD

**Issue by dhinesh20022806** [aykutkardas/regexlearn.com#375]
**Step Number:** `12`
**Step Name:** `examples.negatedCharacterSet.title`
**Language:** `en`
**Version:** `v2.29.0`

**User Agent:** 
`Mozilla/5.0 (X11, Linux x86_64, rv:127.0) Gecko/20100101 Firefox/127.0`

---

**What is the problem you are experiencing?**
Write down the expression that will match anything other than the words beor and beur in the text. Do this using the negated character set

Eventhough , I submit answer that refer from show answer, it fails and i can't move next question ?

![image](https://github.com/aykutkardas/regexlearn.com/assets/105573915/c1139e2d-f21a-4b54-873c-f7af3137d325)

**Comment by aykutkardas** [comment]
Maybe you forgot a space at the beginning of your input?

**Comment by dhinesh20022806** [comment]
yeah , its about space . I am adding extra space in beginning of the input. which is not recognizable.
