### ISSUE TITLE
[Learn]: Type the title here...after i have typed ok and pressed Enter, I was not taken to the next step

### ISSUE THREAD

**Issue by nkemdilimjulie** [aykutkardas/regexlearn.com#383]
**Step Number:** `0`
**Step Name:** `steps.starter.title`
**Language:** `en`
**Version:** `v2.30.0`

**User Agent:** 
`Mozilla/5.0 (X11, Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`

---

**What is the problem you are experiencing?**

**Comment by aykutkardas** [comment]
Did you try uppercase? `OK`
