### ISSUE TITLE
[Learn]: Type the title here...

### ISSUE THREAD

**Issue by annguyenquang** [aykutkardas/regexlearn.com#407]
**Step Number:** `11`
**Step Name:** `examples.characterSet.title`
**Language:** `en`
**Version:** `v2.30.0`

**User Agent:** 
`Mozilla/5.0 (Windows NT 10.0, Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0`

---

**What is the problem you are experiencing?**
I type exactly like the answer but it not let me pass
![image](https://github.com/user-attachments/assets/f8aa3a96-ba5f-4d1d-bed2-1d9a420b9452)

**Comment by aykutkardas** [comment]
It looks like you left a `space` after the `r`.
