### ISSUE TITLE
[Learn]: Solution not accepted, Positive Lookbehind: (?<=)

### ISSUE THREAD

**Issue by luluke87** [aykutkardas/regexlearn.com#41]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**

I have entered the following expression, which is not accepted as a correct solution. However the same solution is provided when using Option+h to get a hint. 

'(?<=\$)\d+'

**Comment by luluke87** [comment]
Even when copying the solution from Line 533ff from the json file, it does not work: 
}
    "title": "steps.positiveLookbehind.title",
    "description": "steps.positiveLookbehind.description",
    "originalTitle": "Lookarounds: Positive Lookbehind",
    "content": "Product Code: 1064 Price: $5",
    "initialFlags": "g",
    "flags": "g",
    "initialValue": "\\d+",
    "regex": ["(?<=\\$)\\d+"],
    "answer": ["5"]
}

**Comment by Iksas** [comment]
The same problem occurs in question 48. Lookbehinds seem to be broken in general.

**Comment by aykutkardas** [comment]
> The same problem occurs in question 48. Lookbehinds seem to be broken in general.

I noticed that this problem is mostly on mobile devices. I'll make a fix that resolves this as soon as possible.

**Comment by aykutkardas** [comment]
Refresh the page and try again.

**Comment by luluke87** [comment]
It is accepting the solution now. However the "5" is not marked in green!

**Comment by aykutkardas** [comment]
Unfortunately, it won't work as Safari doesn't support it, but it no longer blocks you to move on to the next steps. I will add a warning to users using safari for these steps later.

**Comment by daletman** [comment]
> Unfortunately, it won't work as Safari doesn't support it, but it no longer blocks you to move on to the next steps. I will add a warning to users using safari for these steps later.

I’m using Brave on iOS and can’t move on to the next step
