### ISSUE TITLE
[Learn]: Wrong description in step 32.

### ISSUE THREAD

**Issue by Neinei0k** [aykutkardas/regexlearn.com#47]
**Step Number:** `32`
**Step Name:** `steps.groupReference.title`
**Language:** `en-us`

---
"To avoid typing (\d{3}) again at the end of our expression, reference this group by typing \1." This is true for the `444-0-444` that is given but not true in general. The reference \1 is not reference to a regular expression but to an exact text that this regular expression matched. For example, if we have `444-0-111`, then `(\d{3})-(\d)-\d{3}` will match it, but `(\d{3})-(\d)-\1` will not.

**Comment by aykutkardas** [comment]
Fixed 🎉

**Comment by Neinei0k** [comment]
> Fixed

As far as I can see, it's not. Also, I checked and didn't see any other similar issue, so it is not a duplicate.

**Comment by aykutkardas** [comment]
The examples and explanations in these steps have been updated. ✨

**Comment by Neinei0k** [comment]
Sorry to do this again, but in the new description: "The first group is a non-capture group. Therefore it cannot be referenced.", but the first part of regular expression is `(ha)-\1`. It is a capturing group and it uses a reference.

**Comment by aykutkardas** [comment]
You're right, I just noticed it now. I think the texts got mixed up. I'm updating to the latest it should be. Can you please review again? @Neinei0k 

![image](https://user-images.githubusercontent.com/7966133/142719710-342a9fd8-d8f9-4aeb-ad62-61f1ff9a3ec3.png)


Thanks for your feedback. ✨

**Comment by Neinei0k** [comment]
I think it should be made clear that `\1` means that it matches the same text that the first group matches. Someone who never used regular expressions might not get this from this description. Particularly the usage of words "to avoid rewriting" could be interpreted the same way as it was before all the changes, that `\1` could just be replaced by the contents of the capturing group, which is obviously wrong. Maybe write something like "`\1` will be substituted with the text matched by the first capturing group".
