### ISSUE TITLE
[Learn]:  `pipeCharacter` There is a better expression for the sample.

### ISSUE THREAD

**Issue by pappanick** [aykutkardas/regexlearn.com#48]
**Step Number:** `34`
**Step Name:** `steps.pipeCharacter.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**
I think this is a better solution:(C|c|r)at

**Comment by aykutkardas** [comment]
You're right. But if you did, you would think that you could only alternate between characters. The point of this example is that you can use a pipe between both characters and expressions.
