### ISSUE TITLE
[Learn]: ‘positiveLookbehind‘ Correct answer is not accepted.

### ISSUE THREAD

**Issue by bjacobgordon** [aykutkardas/regexlearn.com#49]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**
Entered expressions (?<=\$)\d+ doesn't allow me to continue to the next question despite matching the answer.

   
![Screen Shot 2021-11-17 at 8 42 35 AM](https://user-images.githubusercontent.com/61476868/142221756-ba7ceae6-045c-4515-9bff-3da730910166.png)

**Comment by aykutkardas** [comment]
Which browser are you using?

**Comment by bjacobgordon** [comment]
Safari 15.1

**Comment by aykutkardas** [comment]
https://caniuse.com/js-regexp-lookbehind

The problem seems to be that safari doesn't support this step. I'll find a way to get this working for people who prefer to use Safari. In the worst case, you will be able to pass these steps and continue training tomorrow.

**Comment by aykutkardas** [comment]
Refresh the page and try again.

**Comment by bjacobgordon** [comment]
Works, thanks!
