### ISSUE TITLE
[Learn]:  Braces can be used instead of Curly Braces.

### ISSUE THREAD

**Issue by mxtbcca** [aykutkardas/regexlearn.com#50]
**Step Number:** `20`
**Step Name:** `steps.quantifier.title`
**Language:** `en-us`

---
No problem but a comment.
It may be more accurate to have the title be just "Braces - 1"
From typography:
( ) are called parentheses
[ ] are called brackets
{ } are called braces
reference, https://practicaltypography.com/parentheses-brackets-and-braces.html

**Comment by aykutkardas** [comment]
Nice suggestion, but I think curly braces are more common. 

Thanks for your feedback. 🙏🏻
