### ISSUE TITLE
[Learn]: The explanation text uses \d to match integers but the regex give uses [0-9]. \d hasn't been explained yet at this point.

### ISSUE THREAD

**Issue by rob-land** [aykutkardas/regexlearn.com#52]
**Step Number:** `32`
**Step Name:** `steps.groupReference.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**

**Comment by rob-land** [comment]
The explanation text uses \d to match integers but the regex give uses [0-9]. \d hasn't been explained yet at this point.

**Comment by aykutkardas** [comment]
Fixed 🎉
