### ISSUE TITLE
[Learn]:  wording is confusing in `examples.quantifier.title` 

### ISSUE THREAD

**Issue by Kren** [aykutkardas/regexlearn.com#54]
**Step Number:** `27`
**Step Name:** `examples.quantifier.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**
I think the wording is confusing. You could say "4 digit numbers" 
or "numbers with a length of 4" instead of "4 of the numbers"

**Comment by aykutkardas** [comment]
Thanks, fixed. 🎉
