### ISSUE TITLE
[Learn]: PositiveLookBehind Not Accepting Working Answer /(?<=\$)\d+/g

### ISSUE THREAD

**Issue by mbennette68** [aykutkardas/regexlearn.com#63]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**
Can't proceed beyond Positive Look Behind Section even after entering the correct RegEx pattern, which I had to get from the help link:

I am using Safari on MacBook Pro M1 but don't know if issue is the browser or not.

![image](https://user-images.githubusercontent.com/16678277/142289065-4ae629f9-45ea-46ef-8e13-a7663e3aa47a.png)

Thank you!

**Comment by aykutkardas** [comment]
Unfortunately Safari doesn't support these "lookbehind" statements. I'm considering adding a warning about this.  😔 

You should be able to pass the step when you type the correct expression, even if it doesn't highlight anymore.

https://github.com/aykutkardas/regexlearn.com/issues/49#issuecomment-971692699

**Comment by samkeet** [comment]
Is there a workaround for this issue on an iPhone? I'm using Safari on iOS 15.1
 ![image](https://user-images.githubusercontent.com/25041447/142606698-8063e576-53d9-4f8e-86e0-819ece628789.png)

**Comment by aykutkardas** [comment]
<img width="886" alt="CleanShot 2021-11-20 at 00 02 26@2x" src="https://user-images.githubusercontent.com/7966133/142691355-b954223c-68db-4b70-8db8-ee8b2137d2ce.png">
