### ISSUE TITLE
[Learn]: 

### ISSUE THREAD

**Issue by dirtyv** [aykutkardas/regexlearn.com#67]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**

This also applies to 48:
The text block does not highlight what the regex is supposed to be selecting. Using Safari 15.1 on MacBook M1
    
<img width="839" alt="Screen Shot 2021-11-17 at 11 04 36 PM" src="https://user-images.githubusercontent.com/60368496/142349697-13520af3-80c0-4f17-a418-a8720951a9e1.png">

P.S. Awesome tool, thank you for making it!

**Comment by aykutkardas** [comment]
Safari unfortunately does not support lookbehind. So there is no way to show it. I will add a warning text about this soon.

> P.S. Awesome tool, thank you for making it!

Thank you 🎉
