### ISSUE TITLE
[Learn]:  better expression for `pipe` sample

### ISSUE THREAD

**Issue by agileAlligator** [aykutkardas/regexlearn.com#68]
**Step Number:** `34`
**Step Name:** `steps.pipeCharacter.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**

A better solution would be: (C|c|r)at instead of the given solution [(C|c)at|rat]

(C|c|r)at would better explain the concept of pipe operator

**Comment by aykutkardas** [comment]
What do you think about that? https://github.com/aykutkardas/regexlearn.com/issues/48#issuecomment-971819352
