### ISSUE TITLE
[Learn]: Grammar problem in `positiveLookbehind`

### ISSUE THREAD

**Issue by agileAlligator** [aykutkardas/regexlearn.com#69]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**

Problem Given:

>Product Code: 1064 Price: $5

> For example, we want to select the price value in the text. Therefore, to select only the number values that *precede* $

The price *succeeds* the "$".

I think it was meant to be "preceded by the $"
    
A precedes B — A happened first.

A preceded by B — B happened first.

Same type of error is found in 48th question. Please fix

**Comment by aykutkardas** [comment]
Thanks. Fixed 👍🏻
