### ISSUE TITLE
[Learn]: 

### ISSUE THREAD

**Issue by shreyaprakasan** [aykutkardas/regexlearn.com#79]
**Step Number:** `47`
**Step Name:** `steps.positiveLookbehind.title`
**Language:** `en-us`

---

**What is the problem you are experiencing?**
The correct regex pattern doesn’t pass in this step.

**Comment by aykutkardas** [comment]
If you are using safari these steps are not supported by Safari but you will see a warning message asking you to click to skip. Try refreshing the page.
