### ISSUE TITLE
[Lang]: please add `Chinese` language

### ISSUE THREAD

**Issue by oiuv** [aykutkardas/regexlearn.com#80]
please add chinese language, thanks

**Comment by 827597924** [comment]
请加中文，谢谢

**Comment by mzivv** [comment]
please add chinese language

**Comment by isPoto** [comment]
I'll translate it into Chinese.

**Comment by aykutkardas** [comment]
Related PR: #101

**Comment by dabingooo** [comment]
please add chinese language,thanks.

**Comment by isPoto** [comment]
> please add chinese language,thanks.

The Chinese has been translated successfully and is waiting for the developers to merge it into the project for release. However, my friend made a preview version with his own server, and you can experience it right now

https://regexlearn-com.vercel.app/zh

You can post translation problems you encounter here.

https://meta.appinn.net/t/topic/28243/12?u=poto

**Comment by elicec** [comment]
go  go  go

**Comment by xiaolitongxue666** [comment]
Please add chinese language

**Comment by aykutkardas** [comment]
> Please add chinese language

It will be added today.

**Comment by aykutkardas** [comment]
Hi everyone,

Could you please review the changes in this PR #103  and let me know if they are ok? When I tried to check some of the translations, I noticed that they were not descriptive enough or there were incorrect expressions.

@xiaolitongxue666 
@elicec 
@dabingooo 
@mzivv 
@oiuv

**Comment by xiaolitongxue666** [comment]
@aykutkardas I just trans a simple verison for myself  , I will review you PR soon , thank for you work !

**Comment by Mendax0s** [comment]
请添加中文，谢谢

**Comment by focuseds** [comment]
thank you for adding Chinese!

**Comment by aykutkardas** [comment]
🎉 🎉 🎉 

Added `Chinese` support now. Thanks to @isPoto. (#111) 

If you have a problem with the translation, feel free to create a problem.

https://regexlearn.com/zh-cn

**Comment by oiuv** [comment]
great, thanks
