### ISSUE TITLE
[Learn]: 'Show answer' and then go to next question, answer still visible

### ISSUE THREAD

**Issue by mrfy** [aykutkardas/regexlearn.com#82]
**Step Number:** `11`
**Step Name:** `examples.characterSet.title`
**Language:** `en-us`

**User Agent:** `Chrome/96.0.4664.45`

---

**What is the problem you are experiencing?**
If I click 'show answer' and the go to next question, the next answer is visible. Please hide next answer.

**Comment by aykutkardas** [comment]
Thanks for reporting it. Fixed. 🚀
