### ISSUE TITLE
[Learn]: regex matching does not work correctly in Character Sets

### ISSUE THREAD

**Issue by dandoonian** [aykutkardas/regexlearn.com#83]
**Step Number:** `4`
**Step Name:** `steps.characterSet.title`
**Language:** `en-us`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36`

---

**What is the problem you are experiencing?**

![image](https://user-images.githubusercontent.com/4948197/143837358-58558294-e3c0-4c25-8b36-a6eeefd8e554.png)

bur is not selected (although it's not the right answer to this question)

**Comment by aykutkardas** [comment]
Have you tried "Show Answer"? `[OPTION + H]`  There should be no commas.

**Comment by aykutkardas** [comment]
> (although it's not the right answer to this question)

You are right with this edit. I will fix this..

**Comment by aykutkardas** [comment]
Thanks for reporting it. Fixed. 🚀
