### ISSUE TITLE
[Learn]: Unclear what the ask is

### ISSUE THREAD

**Issue by mandy-chan** [aykutkardas/regexlearn.com#90]
**Step Number:** `33`
**Step Name:** `steps.nonCapturingGroupping.title`
**Language:** `en-us`

**User Agent:** 
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36`

---

**What is the problem you are experiencing?**

Not really a problem, but unclear on what the ask is for 33. Am I suppose to group it such that I'm capturing the second group? Love this product btw!

**Comment by aykutkardas** [comment]
Thanks for the feedback, @mandy-chan. I will make this more understandable.

**Comment by aykutkardas** [comment]
This step updated. 🎉
