### ISSUE TITLE
[Lang]: Add `Korean` localization support

### ISSUE THREAD

**Issue by aykutkardas** [aykutkardas/regexlearn.com#92]
Is there anyone who can contribute to this translation? 

---
With a little help it could be live in Korean.

https://github.com/aykutkardas/regexlearn.com/pull/223

**Comment by Young-mason** [comment]
Hi, I'll be happy if I can contribute to add Korean translation 🙂

**Comment by aykutkardas** [comment]
> Hi, I'll be happy if I can contribute to add Korean translation 🙂

Cool, I'm here if you have any questions. 👋🏻

**Comment by Young-mason** [comment]
> 

Thaanks! 🙌
It's my first time to contribute to open-source, 
I'd like to know about proper process to contribute! 🙏
I'm thinking I add Korean translation JSON files to localization/ko and send PR is that OK ?

**Comment by aykutkardas** [comment]
Here is an translation PR #84 . Following the same steps may help.

**Comment by ro-ko** [comment]
hello, here is PR #95 for korean localization update. If there is some problem, send me again I'll modify

**Comment by aykutkardas** [comment]
@ro-ko Thanks, I will review

@Young-mason  If you haven't started and you want to, you can help by checking the changes here.

**Comment by aykutkardas** [comment]
With a little help it could be live in Korean. 

#223
