### ISSUE TITLE
[Lang]: Checking and developing `Russian` translations

### ISSUE THREAD

**Issue by aykutkardas** [aykutkardas/regexlearn.com#97]
Also, I think someone can correct my translation in this translation keys:
- https://github.com/aykutkardas/regexlearn.com/blob/a1d63ac23237863087a09a7caa38aa3db5276d4b/src/localization/ru/cheatsheet.json#L51-L54
- https://github.com/aykutkardas/regexlearn.com/blob/a1d63ac23237863087a09a7caa38aa3db5276d4b/src/localization/ru/learn.json#L128-L141

(make translation more understandable)

_Originally posted by @LWJerri in https://github.com/aykutkardas/regexlearn.com/issues/96#issuecomment-988164983_

**Comment by Ninelka** [comment]
Checked and improved https://github.com/aykutkardas/regexlearn.com/pull/137

**Comment by LWJerri** [comment]
Yeap, I think we can accept this PR.

**Comment by aykutkardas** [comment]
Thanks. 🎉
